name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - run: |
          git config user.name owatu
          git config user.email oaoto1811@gmail.com
          git add -f docs
          git commit -m "Build for Github Pages" -m "By Github Actions"
          git push
